-- =====================================================================
-- PulsePass V1 - Esquema base
-- Cubre: BR-001..BR-009, NFR-001, NFR-002, NFR-003, NFR-008
-- Esta migracion NO debe modificarse una vez aplicada (ver pregunta 4 del PRD).
-- =====================================================================

-- ---------------------------------------------------------------------
-- venues  (FR-VEN-001, FR-VEN-002, FR-VEN-003)
-- ---------------------------------------------------------------------
CREATE TABLE venues (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code     VARCHAR(50)  NOT NULL,
    name     VARCHAR(150) NOT NULL,
    city     VARCHAR(100) NOT NULL,
    address  VARCHAR(255),
    capacity INTEGER      NOT NULL,
    active   BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_venues_code      UNIQUE (code),
    CONSTRAINT ck_venues_capacity  CHECK (capacity > 0)
);

-- ---------------------------------------------------------------------
-- events  (FR-EVT-001..FR-EVT-005, BR-001)
-- ---------------------------------------------------------------------
CREATE TABLE events (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_code  VARCHAR(50)   NOT NULL,
    name        VARCHAR(150)  NOT NULL,
    description VARCHAR(1000),
    category    VARCHAR(30)   NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    event_date  TIMESTAMP     NOT NULL,
    minimum_age INTEGER       NOT NULL DEFAULT 0,
    venue_id    BIGINT        NOT NULL,

    CONSTRAINT uk_events_event_code UNIQUE (event_code),
    CONSTRAINT fk_events_venue      FOREIGN KEY (venue_id) REFERENCES venues (id),
    CONSTRAINT ck_events_min_age    CHECK (minimum_age >= 0),
    -- FR-EVT-004: catalogo de categorias reforzado en la BD
    CONSTRAINT ck_events_category   CHECK (category IN
        ('MUSIC', 'SPORTS', 'TECHNOLOGY', 'EDUCATION', 'CULTURE', 'ENTERTAINMENT')),
    -- FR-EVT-003: catalogo de estados reforzado en la BD
    CONSTRAINT ck_events_status     CHECK (status IN
        ('DRAFT', 'PUBLISHED', 'SOLD_OUT', 'CANCELLED', 'FINISHED'))
);

CREATE INDEX idx_events_venue         ON events (venue_id);
CREATE INDEX idx_events_status_date   ON events (status, event_date);

-- ---------------------------------------------------------------------
-- artists  (FR-ART-001, FR-ART-002)
-- ---------------------------------------------------------------------
CREATE TABLE artists (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_name VARCHAR(120) NOT NULL,
    country    VARCHAR(80),
    genre      VARCHAR(80),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_artists_stage_name UNIQUE (stage_name)
);

-- ---------------------------------------------------------------------
-- event_artists : relacion N:M (FR-ART-003, FR-ART-004, BR-003)
-- La PK compuesta impide repetir el mismo par evento-artista.
-- ---------------------------------------------------------------------
CREATE TABLE event_artists (
    event_id  BIGINT NOT NULL,
    artist_id BIGINT NOT NULL,

    CONSTRAINT pk_event_artists        PRIMARY KEY (event_id, artist_id),
    CONSTRAINT fk_event_artists_event  FOREIGN KEY (event_id)  REFERENCES events (id)  ON DELETE CASCADE,
    CONSTRAINT fk_event_artists_artist FOREIGN KEY (artist_id) REFERENCES artists (id) ON DELETE CASCADE
);

CREATE INDEX idx_event_artists_artist ON event_artists (artist_id);

-- ---------------------------------------------------------------------
-- users  (FR-USR-001, FR-USR-002)
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(60)  NOT NULL,
    email    VARCHAR(160) NOT NULL,
    active   BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email)
);

-- ---------------------------------------------------------------------
-- user_profiles : relacion 1:1 (FR-USR-003, FR-USR-004, BR-004)
-- El UNIQUE sobre user_id es lo que hace cumplir el 1:1 en PostgreSQL.
-- ---------------------------------------------------------------------
CREATE TABLE user_profiles (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    phone      VARCHAR(30),
    city       VARCHAR(100),
    birth_date DATE,
    user_id    BIGINT       NOT NULL,

    CONSTRAINT uk_user_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- tickets  (FR-TKT-001..FR-TKT-008, BR-005, BR-006, BR-007)
-- ---------------------------------------------------------------------
CREATE TABLE tickets (
    id            BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_code   VARCHAR(50)    NOT NULL,
    type          VARCHAR(20)    NOT NULL,
    price         NUMERIC(12, 2) NOT NULL,
    status        VARCHAR(20)    NOT NULL,
    purchase_date TIMESTAMP      NOT NULL,
    user_id       BIGINT         NOT NULL,
    event_id      BIGINT         NOT NULL,

    CONSTRAINT uk_tickets_ticket_code UNIQUE (ticket_code),
    CONSTRAINT fk_tickets_user        FOREIGN KEY (user_id)  REFERENCES users (id),
    CONSTRAINT fk_tickets_event       FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT ck_tickets_price       CHECK (price >= 0),
    CONSTRAINT ck_tickets_type        CHECK (type IN ('GENERAL', 'VIP', 'BACKSTAGE', 'STUDENT')),
    CONSTRAINT ck_tickets_status      CHECK (status IN ('RESERVED', 'PAID', 'CANCELLED', 'USED'))
);

CREATE INDEX idx_tickets_user          ON tickets (user_id);
CREATE INDEX idx_tickets_event_status  ON tickets (event_id, status);
